import { Layout } from '@/types';
import './globals.css';
import AfterHydration from '@/components/AfterHydration';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: Layout = ({
  children,
}) => {
  return (
    <html lang="en">
      <body>
        {children}
        <AfterHydration />
      </body>
    </html>
  );
};
export default RootLayout;
